# Snakefile

rule all:
    input:
        "output/simulated_sequences/recombinants.csv",
        "output/inferred/optimization_results.csv",
        "output/inferred/optimization_results_controls.csv"
        # "output/results/breakpoint_boxplot.png",
        # "output/results/first_20_true_and_inferred.png",
        # "output/results/sens_vs_edits.png"

rule get_mutation_cnt:
    message: "Counting the number of mutations on branches on the usher tree."
    input:
        data="../data/usher.json"
    output:
        "output/mutation_counts/mutation_count"
    shell:
        """
        python3 get_mutation_cnt.py 
        """

rule sim_sequences:
    message: "Simulating recombinant and control sequences."
    input:
        data="../run-on-cluster-3/real-data-analysis/output/sliding_windows/seq_pango_sorted/seq_pango_sorted_2022-11-06_2022-12-11.csv.gz",
        cnt="output/mutation_counts/mutation_count"
    output:
        "output/simulated_sequences/recombinants.csv",
        "output/simulated_sequences/sampled_sequences.csv",
        "output/simulated_sequences/breakpoints.csv",
        "output/simulated_sequences/controls.csv",
        "output/simulated_sequences/sampled_sequences_control.csv"
    shell:
        """
        python3 sim_sequences.py --csv {input.data} --rate 0.0002 --n_single 500 --n_double 500 --n_control 1000 --no-plot
        """

rule run_HMM:
    threads: 30
    message: "Running the hidden Markov model to infer the parental lineages for the simulated recombinant sequences."
    input:
        freq="../run-on-cluster-3/real-data-analysis/output/sliding_windows/allele_frequencies/allele_freq_matrix_2022-11-06_2022-12-11.csv.gz",
        test="output/simulated_sequences/recombinants.csv",
        pi="../run-on-cluster-3/real-data-analysis/output/sliding_windows/allele_frequencies/initial_pi_2022-11-06_2022-12-11.json"
    output:
        out="output/inferred/inferred_lineages.json",
        optim_out="output/inferred/optimization_results.csv"
    shell:
        """
        python3 ../run-on-cluster-3/code/run_HMM.py --freq {input.freq} --test {input.test} --pi {input.pi} --out {output.out} --optim_out {output.optim_out} --cpu 30
        """

rule run_HMM_controls:
    threads: 30
    message: "Running the hidden Markov model to infer the parental lineages for the simulated control sequences."
    input:
        freq="../run-on-cluster-3/real-data-analysis/output/sliding_windows/allele_frequencies/allele_freq_matrix_2022-11-06_2022-12-11.csv.gz",
        test="output/simulated_sequences/controls.csv",
        pi="../run-on-cluster-3/real-data-analysis/output/sliding_windows/allele_frequencies/initial_pi_2022-11-06_2022-12-11.json"
    output:
        out="output/inferred/inferred_lineages_controls.json",
        optim_out="output/inferred/optimization_results_controls.csv"
    shell:
        """
        python3 ../run-on-cluster-3/code/run_HMM.py --freq {input.freq} --test {input.test} --pi {input.pi} --out {output.out} --optim_out {output.optim_out} --cpu 30
        """

# rule analyze_sim_results:
#     message: "Analyzing simulation results."
#     input:
#         "output/inferred/inferred_lineages.json",
#         "output/inferred/optimization_results.csv",
#         "output/inferred/inferred_lineages_controls.json",
#         "output/inferred/optimization_results_controls.csv",
#     output:
#         "output/results/breakpoint_boxplot.png",
#         "output/results/first_20_true_and_inferred.png",
#         "output/results/sens_vs_edits.png"
#     shell:
#         """
#         python3 analyze_sim_results.py
#         """